### REGISTER

POST http://localhost:8080/api/v1/users
Accept: application/json
Content-Type: application/json

{
  "username": "solahkay1234",
  "name": "Solahudin",
  "email": "solah1234@example.com",
  "password": "rahasia"
}

### GET USER

GET http://localhost:8080/api/v1/users/solahkay12
Accept: application/json

### UPDATE USER

PATCH http://localhost:8080/api/v1/users/solahkay
Accept: application/json
Content-Type: application/json

{
  "name": "Solahudin Al Malibari",
  "password": "secret"
}

### DELETE USER

DELETE http://localhost:8080/api/v1/users/delete/solahkay
Accept: application/json
Content-Type: application/json

{
  "password": "secret"
}

### CREATE MERCHANT

POST http://localhost:8080/api/v1/merchants
Accept: application/json
Content-Type: application/json

{
  "name": "Nexian",
  "location": "Garut"
}

### GET MERCHANT

GET http://localhost:8080/api/v1/merchants/Nexian
Accept: application/json

### UPDATE STATUS MERCHANT

PATCH http://localhost:8080/api/v1/merchants/Nexian
Accept: application/json
Content-Type: application/json

{
  "status": "OPEN"
}

### GET ALL ONLINE MERCHANT

GET http://localhost:8080/api/v1/merchants/online?page=1
Accept: application/json

### CREATE PRODUCT

POST http://localhost:8080/api/v1/products
Accept: application/json
Content-Type: application/json

{
  "name": "Xioami x12",
  "price": 18000000,
  "quantity": 13,
  "merchantName": "Xioami"
}

### GET PRODUCT

GET http://localhost:8080/api/v1/products/XIOAMI-X1P-66016
Accept: application/json

### UPDATE PRODUCT

PATCH http://localhost:8080/api/v1/products/XIOAMI-XP1-70544
Accept: application/json
Content-Type: application/json

{
  "price": 10000000,
  "quantity": 0,
  "merchantName": "Xioami"
}

### GET ALL AVAILABLE PRODUCT

GET http://localhost:8080/api/v1/products
Accept: application/json

### DELETE PRODUCT

DELETE http://localhost:8080/api/v1/products/XIOAMI-XR1P6-46960
Accept: application/json
Content-Type: application/json

{
  "merchantName": "Xioami"
}

### CREATE ORDER

POST http://localhost:8080/api/v1/orders
Accept: application/pdf
Content-Type: application/json

{
  "shippingAddress": "Pabuaran Mekar, Cibinong",
  "orderDetails": [
    {
      "productSku": "SUMSANG-SGGN-73948",
      "quantity": 1
    },
    {
      "productSku": "XIOAMI-XP6-48872",
      "quantity": 3
    }
  ],
  "username": "solahkay"
}

### GET ORDER
GET http://localhost:8080/api/v1/orders/INV-20231022-000001
Accept: application/json

### GET ALL ORDER
GET http://localhost:8080/api/v1/orders?username=solahkay
Accept: application/json
